### ISSUE TITLE
support providing terraform vars to a new environment

### ISSUE THREAD

**Issue by punkle** [env0/env0-client-integrations#78]
The API appears to support this, it would be great if the cli also supported this.

https://github.com/env0/env0-client-integrations/blob/3fed29e5b0411aff9bb0b97fe98cecbc99197dd1/node/src/commands/deploy.js#L22

**Comment by omry-hay** [comment]
@punkle - thanks for the feedback, we will get on it.
In the meantime you can always use the `TF_VAR` convention for adding Terraform variables using environment variables - [see this](https://www.terraform.io/docs/language/values/variables.html#environment-variables)

**Comment by punkle** [comment]
I had figured that out in the meantime, Great minds think alike. :) Thanks for the speedy response.

**Comment by away168** [comment]
https://www.terraform.io/language/values/variables#variable-definition-precedence

due to variable precedence, environment vars get overwritten if we also have the variable defined in the template.

which currently forces the template to only use environment variables when we also want to use the env0 cli.

**Comment by away168** [comment]
This has now been added in 1.0.16 of the CLI.
